### PR TITLE
463: Added social buttons to mobile menu

### LINKED ISSUE #463: Social buttons for mobile
Social buttons are now hidden on mobile. Mobile design should be updated accordingly.

### PR DESCRIPTION
**Pull request by piersss**
Fixes #463

### CODE REVIEW

**Review by GiuntaLucas — APPROVED** [review]
It's working perfectly. But i have a small question, What do you think to place the button at the bottom of the screen ? As a user experience, maybe it will be better to not see the share button at the same lvl of the menu, and to avoid an overlay when you touch the social button with some locale. 

image

**Comment by piersss** [comment]
> It's working perfectly. But i have a small question, What do you think to place the button at the bottom of the screen ? As a user experience, maybe it will be better to not see the share button at the same lvl of the menu, and to avoid an overlay when you touch the social button with some locale.
> 
> image

Yup, you're right. Will add this.

**Review by GiuntaLucas — APPROVED** [review]
Impecable ! Perferct !

**Comment by 2xAST** [comment]
In safari on iPhone the buttons are below the url bar, so they are not visible and you can't scroll down to them

**Comment by piersss** [comment]
> In safari on iPhone the buttons are below the url bar, so they are not visible and you can't scroll down to them

Whoops, same on android. Maybe aligning it to the bottom wasn't so smart. 🧐

**Pull request merged**
