### PR TITLE
Feature/433 xdefi wallet

### PR DESCRIPTION
**Pull request by GiuntaLucas**
- Add support of xDefi
- Follow the same logic of metamask when xDefi is not installed (change text + redirect to xDefi web page)

Ticket: https://github.com/airswap/airswap-web/issues/433

Warning: xDefi act like Metamask, when metamask is already installed, metamask will be open instead of xDefi until the user will activate an option from his xDefi wallet to be priority.

get metamask
connect

### CODE REVIEW

**Review by piersss — CHANGES_REQUESTED** [review]
Hey LeHardy

I never used xdefi wallet so I will install it later this week and test things out.

This MR has a lot of overlap with the metamask button MR. So you can use the same feedback here.

**Comment by piersss** [comment]
Steps I took:
1. Open incognito browser with xdefi as only extension
2. Enabled "Prioritise XDEFI" (or else it won't connect anyway)
3. Open web app and connect wallet
4. It injects the wallet but the registry tokens are not filled

After connecting the wallet the registry tokens are not filled. It fails silently in registryApi.ts, line 20:

```
  const [addEvents, removeEvents] = await Promise.all([
    registryContract.queryFilter(addTokensEventFilter),
    registryContract.queryFilter(removeTokensEventFilter),
  ]);
```

Wrapping it around a try catch I get this error:

```
base-provider.ts:1607 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at Web3Provider.<anonymous> (base-provider.ts:1607:1)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.ts:2:1)
```

My guess is that xdefi is not fully compatible with some ethers.js functions. This is a tough one.

**Review by robbestad — CHANGES_REQUESTED** [review]
It's necessary to rebase this to the current `develop` and go from there. I also concur with the feedback left from Pierss

**Comment by dmosites** [comment]
Closing until there's a clear path froward.

**Pull request closed without merging**
