### PR TITLE
Fix/remove tailwind

### PR DESCRIPTION
**Pull request by piersss**
Remove all traces of tailwind. Tailwind global styling was still needed, so I moved it to GlobalStyle.ts.

All seems to work fine, tested the app and storybook in chrome, FF and safari.

### CODE REVIEW

**Review by codyenokida — APPROVED** [review]
LGTM!

**Comment by gpxl-dev** [comment]
Personally I lean towards putting the reset styles in a different file as this adds a lot of noise. Thoughts on this?

**Comment by piersss** [comment]
Yeah sure, I can add a resetStyle file.

**Review by gpxl-dev — COMMENTED** [review]
:shipit:

**Pull request merged**
