### PR TITLE
feat: add thai locale

### PR DESCRIPTION
**Pull request by goffxnca**
added full thai translation for the airswap web interface. i’m a native thai speaker, so everything’s accurate and makes sense culturally. translations directly mirror the 258 english keys as of today.

Screenshot 2567-11-09 at 01 05 40

### CODE REVIEW

**Comment by seroendeng** [comment]
Very cool. Much appreciated. 🙏

**Comment by makkelie-dev** [comment]
Very cool. Much appreciated. 🙏 🇹🇭

**Review by makkelie-dev — APPROVED** [review]
LGTM

**Comment by goffxnca** [comment]
> LGTM

Khob Khun Krub! 🙏🚀

**Pull request merged**
