### PR TITLE
Update to 3.0.0-beta

### PR DESCRIPTION
**Pull request by dmosites**

### CODE REVIEW

**Review by robbestad — APPROVED** [review]

**Review by robbestad — CHANGES_REQUESTED** [review]
On build I  get
```./node_modules/@airswap/libraries/node_modules/@airswap/utils/build/src/hashes.js
Module not found: Can't resolve '@airswap/types' in '/home/svena/develop/airswap/airswap-web/node_modules/@airswap/libraries/node_modules/@airswap/utils/build/src'```

**Comment by dmosites** [comment]
You've don't yarn install?

**Review by robbestad — APPROVED** [review]

**Review by Phasor — APPROVED** [review]
App installs and runs locally on my machine, swaps work and use swap.sol now and nto light.sol.

**Comment by robbestad** [comment]
> You've done yarn install?

this is resolved now with the latest changes

**Comment by dmosites** [comment]
Tested locally with success: ETH/DAI, WETH/DAI, DAI/ETH, DAI/WETH, ETH/WETH, WETH/ETH

**Pull request merged**
