### PR TITLE
Feature/457 mobile design

### LINKED ISSUE #457: Implement mobile design
New mobile design is under _Latest version_:

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=77%3A1014

### PR DESCRIPTION
**Pull request by piersss**
Closes #457 

Main changes:
- Removed Temporary landing page
- Fully responsive app for desktop, tablet and mobile
- New top bar for mobile and tablet portrait (<768px)
- New mobile toolbar menu on mobile and tablet portrait (<768px)
- Transactions list is now a full screen menu on mobile
- New mobile menu in transactions list with "View on etherscan", "Copy address", and "Disconnect" buttons
- Added mobile and desktop sizes in typography

https://user-images.githubusercontent.com/86911296/150287047-8915f6eb-30cf-4eb2-a51a-105ca90433fb.mov

Original design under "Latest version":

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=77%3A1014

Tested it on android metamask app. Anyone with iphone who could test?

### CODE REVIEW

**Comment by dmosites** [comment]
Everything look good. Small visual issue with the border gradient (both light and dark) on iPhone (ignore the grey box):
IMG_5569

**Comment by robbestad** [comment]
will test it with iPhone now

**Comment by Phasor** [comment]
I had a look at this. Looks really good, only a few comments:

1. We don't seem to check what network we are connected to. Would it be worth asking the user to switch to Ethereum if their wallet is connected to say Polygon or something else, or at least display what network they are currently on somewhere?
2. The System and Light themes seem the same to me (maybe I'm missing something, it is the same on the live website)
3. Is it worth adding the social links to the bottom of the mobile page?
4. When connected to Rinkeby, when I tried to swap from WETH to ETH, I got the following errors:
image
image

Thanks

**Comment by piersss** [comment]
> I had a look at this. Looks really good, only a few comments:
> 
> 1. We don't seem to check what network we are connected to. Would it be worth asking the user to switch to Ethereum if their wallet is connected to say Polygon or something else, or at least display what network they are currently on somewhere?
> 2. The System and Light themes seem the same to me (maybe I'm missing something, it is the same on the live website)
> 3. Is it worth adding the social links to the bottom of the mobile page?
> 4. When connected to Rinkeby, when I tried to swap from WETH to ETH, I got the following errors:
> 
> Thanks

Hey Phasor, thanks for testing.

1. This is a good point but beyond the scope of this ticket, please take it up with Don if we have a ticket for this already.
2. Yes this works as intended. System theme checks if your OS has support for a light/dark theme preference.
3. Jop left it out of the mobile design, I will double check if this was really intentional.
4. Yep, I just checked this and it's a bug! Again, beyond the scope of this ticket, can you add a ticket for this too?

**Comment by piersss** [comment]
> will test it with iPhone now

And? 🐙

**Comment by Phasor** [comment]
I created a new ticket for the bug above:
https://github.com/airswap/airswap-web/issues/464

**Pull request merged**
