### PR TITLE
Feature/wallet selection redesign

### PR DESCRIPTION
**Pull request by piersss**
Added restyle of wallet selection and removed react-modal from project

### CODE REVIEW

**Review by gpxl-dev — CHANGES_REQUESTED** [review]
The contents of the modal are great, but the behaviour should be the same as the `TokenSelection` modal.

My original plan was to use a styled version of react-modal to easily achieve this, but given the `TokenSelection` implementation strayed away from this, we should make our own component that can be re-used to achieve the overlay, transition and back button with custom children.

**Comment by piersss** [comment]
> The contents of the modal are great, but the behaviour should be the same as the `TokenSelection` modal.
> 
> My original plan was to use a styled version of react-modal to easily achieve this, but given the `TokenSelection` implementation strayed away from this, we should make our own component that can be re-used to achieve the overlay, transition and back button with custom children.

Ah yes, I will make an overlay component.

**Comment by piersss** [comment]
I have added the Overlay component.

**Review by gpxl-dev — APPROVED** [review]
Looking awesome :ok-hand:

**Pull request merged**
