### PR TITLE
Corrected text for signer balance low

### PR DESCRIPTION
**Pull request by francisldn**
#373 Corrected the wrong text for signer balance low under validator errors.

### CODE REVIEW

**Comment by francisldn** [comment]
Hi @gpxl-dev, it's an easy fix, but would appreciate if you could please review and approve this PR.

**Comment by piersss** [comment]
Hey Francis, I'm not sure what the correct translation it, so lets's wait for @gpxl-dev. Do you have access to the poeditor? All translations changes should be added in there as well. Contact @robbestad or @dmosites for an invite.

**Comment by piersss** [comment]
> #373 Corrected the wrong text for signer balance low under validator errors.

_Fixes #373_ will link the issue.

**Review by gpxl-dev — APPROVED** [review]

**Comment by gpxl-dev** [comment]
@piersss its possible/likely that this is an English locale only issue as the values for these two keys were the wrong way around

**Comment by robbestad** [comment]
> @piersss its possible/likely that this is an English locale only issue as the values for these two keys were the wrong way around

agree

**Pull request merged**
